name: Run Ruby Script

on: [push]

jobs:
  run-ruby-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Run Ruby script
      run: ruby Firstscript.rb
