name: Run MySQL Script

on: [push]

jobs:
  run-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: |
        dockerize -wait tcp://localhost:3306 -timeout 1m
      env:
        MYSQL_ROOT_PASSWORD: root

    - name: Run MySQL script
      run: |
        mysql -h 127.0.0.1 -u root -proot < script.sql
