name: Run MySQL Script

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # Add this line to specify the Java distribution

    - name: Install Dockerize
      run: |
        curl -sSL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | sudo tar -C /usr/local/bin -xzv

    - name: Run dockerize
      run: dockerize -wait tcp://localhost:3306 -timeout 1m
      env:
        MYSQL_ROOT_PASSWORD: root

    # Add other steps as needed
