name: Run MySQL Script

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo 'Waiting for MySQL...'
          sleep 1
        done

    - name: Run MySQL Script
      run: mysql -h 127.0.0.1 -u root -proot testdb < your_script.sql
